version: "2"
services:
  app:
    container_name: spacy_fastapi
    build: .
    volumes:
      - ./:/usr/src/
    ports:
      - "8080:8080"
    mem_limit: 1g
    environment:
      - GUNICORN_CONF=gunicorn.conf.py
